name: Run CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install SBCL
      run: |
        curl -LJ0 https://github.com/roswell/sbcl_bin/releases/download/2.1.1/sbcl-2.1.1-x86-64-linux-binary.tar.bz2 > sbcl.tar.bz2
        tar -xvf sbcl.tar.bz2
        cd sbcl-2.1.1-x86-64-linux || exit 1
        sudo sh install.sh
        cd .. || exit 1
        rm -rf sbcl-2.1.1-x86-64-linux
    - name: Setup Environment
      uses: HatsuneMiku3939/direnv-action@v1
    - name: Load the project
      run: make load
    - name: Build the project
      run: make build
    - name: Test
      run: make test
