name: Run CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install SBCL
      run: sh ci/install-sbcl.sh
    - name: Test Testing Library
      run: make test-tests
    - name: Compile the project
      run: make compile-project
    - name: Test the Window Manager
      run: make test-wm
