name: Run CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install SBCL
      run: make install-sbcl
    - name: Test Testing Library
      run: make test-tests
    - name: Install Xvfb
      run: sudo apt-get install xvfb
    - name: Test the Window Manager
      run: sh ci/run-tests.sh
