name: Run CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install SBCL
      run: sh ci/install-sbcl.sh
    - name: Setup Environment
      uses: HatsuneMiku3939/direnv-action@v1
    - name: Build the project
      run: make build
    - name: Test
      run: make test
