name: Run CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SBCL
      run: |
        curl -LJ0 https://github.com/roswell/sbcl_bin/releases/download/2.1.1/sbcl-2.1.1-x86-64-linux-binary.tar.bz2 > sbcl.tar.bz2
        tar -xvf sbcl.tar.bz2
        sudo sh sbcl-2.1.1-x86-64-linux/install.sh
        # cd sbcl-2.1.1-x86-64-linux
        # sudo sh ./install.sh

